SELECT B.AUTHOR_ID,B.AUTHOR_NAME,A.CATEGORY,SUM(A.PRICE*C.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS C
JOIN BOOK AS A ON A.BOOK_ID=C.BOOK_ID
JOIN AUTHOR AS B ON A.AUTHOR_ID=B.AUTHOR_ID
WHERE C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID,B.AUTHOR_NAME,A.CATEGORY 
ORDER BY 1,3 DESC